export const GET_DATA_PRODUCT = "GET_DATA_PRODUCT";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_IN_CART = "UPDATE_IN_CART";
export const DELETE_iTEM_IN_CART = "DELETE_iTEM_IN_CART";

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';

export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'USERS_LOGOUT_SUCCESS';


export const REGISTER_SUCCESS = 'CREATE_USER_SUCCESS';


export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const SORT_PRODUCT = 'SORT_PRODUCT';
export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const FILTER_PRICE_PRODUCT = 'FILTER_PRICE_PRODUCT';